config/routes.rb
Rails.application.routes.draw do

devise_for :users
  devise_scope :user do
     get "signup", to: "devise/registrations#new"
     get "login", to: "devise/sessions#new"
     get "logout", to: "devise/sessions#destroy"
  end

  root 'artists#index'
  resources :artists
  resources :songs
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new
      if user.has_role? :admin
        can :manage, :all
      elsif user.has_role? :author
        can :create, Status # author can create status
        can :update, Status # author can update status
         can :destroy, Status # #uncomment this line, author can destroy status
        can :read, :all
      else
        can :read, :all
      end

    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs, dependent: :destroy
  mount_uploader :artistpicture, ArtistPictureUploader
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  mount_uploader :songfile, SongfileUploader
end

app/models/user.rb
class User < ActiveRecord::Base
devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable


       ROLES = %i[admin author]

        def roles=(roles)
          roles = [*roles].map { |r| r.to_sym }
          self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
        end

        def roles
          ROLES.reject do |r|
            ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
          end
        end

        def has_role?(role)
          roles.include?(role)
        end




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  # A list of all available artists
  def index
    @artists = Artist.all
  end

  # Add a new artist as a artist
  def new
    @artist = Artist.new
  end

  # Create a artist from the form params
  def create
    if @artist = Artist.create(artist_params)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
  #    p "ID: #{@artist.id}"
    end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])

    if @artist.destroy
      redirect_to artists_path, :notice => "Your song has been deleted successfully."

    else
      redirect_to @artist
    end
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :artistpicture)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,roles:[])
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password,roles:[])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # A list of all available songs
def index
  @songs = Song.all
end

# Add a new song as a user
  def new
    @song = Song.new
  end

  # Create a song from the form params
  def create
    if @song = Song.create(song_params)
      redirect_to songs_path
    else
      render :new
    end
  end

  def show
  @song = Song.find(params[:id])
  #    p "ID: #{@song.id}"
end

def edit
  @song = Song.find(params[:id])
end

def update
  @song = Song.find(params[:id])
  if @song.update(song_params)
    redirect_to @song
  else
    render :edit
  end
end



def destroy
  @song = Song.find(params[:id])

  if @song.destroy
    redirect_to root_path, :notice => "Your song has been deleted successfully."
  else
    redirect_to @song
  end
end

  private

  def song_params
    params.require(:song).permit(:title, :release_date, :songfile, :album, :artist_id)
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:post)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


def index
    @users = User.all
  end

  # Add a new user as a user
    def new
      @user = User.new
    end

    # Create a user from the form params
    def create
      if @user = User.create(user_params)
        redirect_to users_path
      else
        render :new
      end
    end

    def show
    @user = User.find(params[:id])
    #    p "ID: #{@user.id}"
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end



  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to root_path, :notice => "Your user has been deleted successfully."
    else
      redirect_to @users
    end
  end




private

def user_params
  params.require(:user).permit(:name, :email)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
    content_for(:header) { text.to_s }
  end
end

app/views/artists/_artist.html.erb
<div class="col col s12 m6 l3">
  <article class="card-panel hoverable">
    <p><h2><%= link_to artist.name, artist %></h2></p>
      <p><%= link_to artist_path(artist) do %>
          <%= image_tag artist.artistpicture, style: "width:100%;" %>
          <% end %></p>
<span class="grey lighten-5"><%= link_to "Edit", edit_artist_path(artist) %></span>  |  <span class="red lighten-5"><%= link_to "Destroy", artist_path(artist), method: :delete %></span>
</article>
</div>

app/views/artists/edit.html.erb
<h1>Edit the artist:</h1>
<%= form_for(@artist) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :artistpicture %>
<%= f.file_field :artistpicture %>
<br>
<br>
<br>
<%= f.submit "Edit Artist", :class => "btn btn-primary btn-lg green darken-1"%>
<% end %>

app/views/artists/index.html.erb
<h1>Welcome to <i class="fa fa-music"></i>usic Liby</h1>
  <div class="row">
  <%= render @artists %>
</div>

<% if user_signed_in? %>
<%= link_to "Add New Artist", new_artist_path, class: "btn btn-primary btn-lg green darken-1" %>
<% if Artist.exists? %>
<%= link_to "Add Song", new_song_path, class: "btn btn-primary btn-lg green darken-1" %>
<% end %>
<% end %>

app/views/artists/new.html.erb
<h1>Add a new artist:</h1>
<%= form_for(@artist) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :artistpicture %>
<br>
<br>
<%= f.file_field :artistpicture %>
<br>
<br>
<br>
<%= f.submit "Submit Artist", :class => "btn btn-primary btn-lg green darken-1"%>
<% end %>

app/views/artists/show.html.erb
<div class="artist">
  <h1>Artist name:
    <%= @artist.name %></h1>
<p><%= image_tag @artist.artistpicture %></p>
  <span class="btn btn-default grey lighten-5"><%= link_to "Back", root_path %></span>
  <span class="btn btn-default grey lighten-5"><%= link_to "Edit", edit_artist_path(@artist) %></span>
  <span class="btn btn-default grey lighten-5"><%= link_to "Destroy", artist_path(@artist), method: :delete %></span>
</div>
<br />
<% if Song.exists?(artist_id: @artist.id) %>
<h2>All Songs by <%= @artist.name %></h2>
<br />
<div class="row">
  <% @artist.songs.each do |song| %>
  <div class="col col s12 m6 l3">
    <article class="card-panel hoverable">
      <p>
        <h3><%= link_to song.title, song %></h3>
      </p>
    <p><%= link_to song_path(song) do %>
        <%= image_tag song.songfile, style: "width:100%;" %>
        <% end %></p>

      <!--  <p>Song by: <%= link_to song.artist.name, @artist_path %></p> -->
      <span class="grey lighten-5"><%= link_to "Edit", edit_song_path(song) %></span>
      |
      <span class="red lighten-5"><%= link_to "Destroy", song_path(song), method: :delete %></span>
    </article>
  </div>
  <% end %>
  <% else %>
  <h2><%= @artist.name %> does not have any songs in this liby yet!<br />Please add a song.</h2>
  <p><%= link_to "Add New Song", new_song_path, class: "btn btn-primary btn-lg green darken-1" %></p>

    <% end %>
    <br />
    <br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Liby</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
  </head>
  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo left"><i class="fa fa-music"></i>usic Liby</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if Artist.exists? %>
        <li><%= link_to "Artists", artists_path %></li>
        <% end %>
        <% if Song.exists? %>
        <li><%= link_to "Songs", songs_path %></li>
        <% end %>



        <% if user_signed_in? %>
        <li>
          <%= link_to('Edit registration', edit_user_registration_path) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
        <% end %>
        <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
      <% else %>
        <li>
          <%= link_to('Register', new_user_registration_path)  %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
  <body class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
    <% end %>

    <%= yield %>
</body>
</html>

app/views/songs/_song.html.erb
<tr>
    <td><%= link_to song.title, song, style: "font-size: 15px;" %></td>
    <td><%= link_to song_path(song) do %><%= image_tag song.songfile, style: "width:75px;" %><% end %></td>
    <td><%= link_to song.artist.name, artist_path(song.artist) %></td>
    <td><%= song.release_date %></td>
</tr>

app/views/songs/edit.html.erb
<h1>Edit Song:</h1>
<%= form_for(@song) do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :release_date %>
<%= f.text_field :release_date %>
<%= f.label :album %>
<%= f.text_field :album %>
<%= f.label :songfile %>
<%= f.file_field :songfile %>
<br>
<br>
<br>
<%= f.label :artist_id %>
<%= f.collection_select :artist_id, Artist.all, :id, :name, :prompt => true %>
<br>
<br>
<br>

<%= f.submit "Edit Song", :class => "btn btn-primary btn-lg green darken-1"%>
<% end %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Songs</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Artist</th>
          <th>Released</th>
          <th colspan="5"></th>

    </tr>
  </thead>
<tbody>
<%= render @songs %>
</tbody>
</table>
<br>
<%= link_to "Add New Song", new_song_path, class: "btn btn-primary btn-lg green darken-1" %>

app/views/songs/new.html.erb
<h1>Add a new song:</h1>
<%= form_for(@song) do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :release_date %>
<%= f.date_field :release_date %>
<%= f.label :songfile %>
<br>
<br>
<br>
<%= f.file_field :songfile %>
<br>
<br>
<%= f.label :album %>
<%= f.text_field :album %>
<br>

<% if Artist.exists? %>
<br>
<%= f.label :artist_id %>
<%= f.collection_select :artist_id, Artist.all, :id, :name, prompt: true %>
<br>
<% end %>
<br>
<br>
<%= f.submit "Add New Song", class: "btn btn-primary btn-lg green darken-1" %>
<% end %>

app/views/songs/show.html.erb
<article class="song">
  <h1><%= @song.title %></h1>
  <p>Release Date: <%= @song.release_date %></p>
  <p>Album: <%= @song.album %></p>
  <p>Song File: <%= image_tag @song.songfile %></p>
  <!-- <p>See more songs by <%= link_to @song.artist.name, artist_path %></p> -->
  <p>See more songs by <%= link_to @song.artist.name, artist_path(@song.artist) %></p>


  <p class="navigation">
      <span class="btn btn-default grey lighten-5"><%= link_to "Back", root_path %></span>
      <span class="btn btn-default grey lighten-5"><%= link_to "Edit", edit_song_path(@song) %></span>
      <span class="btn btn-default grey lighten-5"><%= link_to "Destroy", song_path(@song), method: :delete %></span>
    </p>
  </article>
  

app/views/users/_user.html.erb
<div class="col col s12 m6 l3">
  <article class="card-panel hoverable">
    <h1><%= user.name %></h1>
    <p>User Email: <%= user.email %></p>
  </article>
</div>

app/views/users/index.html.erb
<div class="row">
  <%= render @users %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>